export {default as Login} from './Login/Login';
export {default as Register} from './Register/Register';
export {default as Home} from './Home/Home';
export {default as Navbar} from './page/Navbar';
export {default as Error404} from './page/Error404';
export {default as Reset} from './Reset/Reset'; 
export {default as Forget} from './Forget/Forget';
export {default as Client} from './Client/Client';
export {default as Livreur} from './Livreur/Livreur';
